version: '2'
services:
  postgres:
    image: postgres:9.5
    container_name: postgres
    environment:
        POSTGRES_PASSWORD: pass4alambic
        POSTGRES_USER: alambic
  alambic_test:
    image: bbaldassari/alambic_test
    command: su - alambic -c "sh /home/alambic/alambic/resources/scripts/alambic_test.sh"
    ports:
    - "3000:3000"
    depends_on:
    - postgres

