version: '3'
services:
  postgres:
    image: postgres:9.5
    container_name: postgres
    environment:
        POSTGRES_PASSWORD: pass4alambic
        POSTGRES_USER: alambic
    volumes:
    - alambic_db:/var/lib/postgresql/data
  alambic_test:
    image: bbaldassari/alambic_test:latest
    command: [ "sh", "/home/alambic/alambic/docker/image_test/alambic_test.sh" ]
    ports:
    - "3000:3000"
    depends_on:
    - postgres
    volumes:
    - alambic_fs:/home/alambic
volumes:
    alambic_db:    
    alambic_fs:

