version: '2'
services:
  alambic:
    image: boris/alambic
    ports: 
    - "3000:3000"
    links: 
    - postgres
  postgres:
    image: postgres:9.5
    environment:
        POSTGRES_PASSWORD: pass4alambic
        POSTGRES_USER: alambic
