version: '2'
services:
  postgres_ci:
    image: postgres:9.5
    container_name: postgres_ci
    environment:
        POSTGRES_PASSWORD: pass4alambic
        POSTGRES_USER: alambic
    volumes:
    - alambic_db:/var/lib/postgresql/data
  alambic_ci:
    image: bbaldassari/alambic_ci:latest
    command: su - alambic -c "sh /home/alambic/alambic/docker/image_ci/alambic_init_start.sh"
    ports:
    - "3000:3000"
    depends_on:
    - postgres_ci
    volumes:
    - alambic_fs:/home/alambic
volumes:
    alambic_db:    
    alambic_fs:
    
