version: '2'
services:
  postgres:
    image: postgres:9.5
    container_name: postgres
    environment:
        POSTGRES_PASSWORD: pass4alambic
        POSTGRES_USER: alambic
  alambic:
    image: bbaldassari/alambic_ci
    command: sh /home/alambic/alambic_init.sh
    ports:
    - "3000:3000"
    depends_on:
    - postgres
