---
output: html_document
---
<div class="row"><div class="col-md-12">
```{r init, echo=FALSE, fig.height=3, message=FALSE, warning=FALSE}
library(knitr)
library(xts)
library(reshape2)
require(ggplot2)

#project.id <- 'alambic'
plugin.id <- 'SonarQube45'

abc <- c('A', 'B', 'C', 'D', 'E', 'F', 'G')

file.metrics = paste("", project.id, "_sq_metrics.csv", sep="")
metrics <- read.csv(file=file.metrics, header=T)
```

### <a name="quick-summary"></a>SonarQube violations

* Total number of violations on project ([SQ_VIOLATIONS](/documentation/metrics#SQ_VIOLATIONS)): ``r metrics[['SQ_VIOLATIONS']]``
* Number of Blocker violations ([SQ_VIOLATIONS_BLOCKER](/documentation/metrics#SQ_VIOLATIONS_BLOCKER)): ``r metrics[['SQ_VIOLATIONS_BLOCKER']]``
* Number of Critical violations ([SQ_VIOLATIONS_CRITICAL](/documentation/metrics#SQ_VIOLATIONS_CRITICAL)): ``r metrics[['SQ_VIOLATIONS_CRITICAL']]``
* Number of Major violations ([SQ_VIOLATIONS_MAJOR](/documentation/metrics#SQ_VIOLATIONS_MAJOR)): ``r metrics[['SQ_VIOLATIONS_MAJOR']]``
* Number of Minor violations ([SQ_VIOLATIONS_MINOR](/documentation/metrics#SQ_VIOLATIONS_MINOR)): ``r metrics[['SQ_VIOLATIONS_MINOR']]``

The SonarQube plugin analysis for project ``r project.id`` is available on the [Alambic dashboard](/projects/`r project.id`/SonarQube45/sonarqube45.html).
