---
title: "Hudson visualisation"
author:
- name: "Boris Baldassari"
  affiliation: Castalia Solutions
output:
  html_fragment:
    toc: false
    fig_caption: true
    fig.width: 800
    self_contained: false
    lib_dir: libs
    echo: false
    dev: svg
---

```{r init, echo=FALSE, message=FALSE}
project.id <- 'modeling.sirius'
plugin.id <- 'hudson'
file.main = paste("", project.id, "_hudson_main.csv", sep="")
file.jobs = paste("", project.id, "_hudson_jobs.csv", sep="")

library(knitr)
library(xts)
library(reshape2)

knitr::opts_chunk$set(fig.path = paste( 'figures/', plugin.id, '/', project.id, '/', sep=""))
#opts_knit$set(progress = TRUE, verbose = TRUE, self.contained=T)

require(ggplot2)
require(xtable)

metrics <- read.csv(file=file.main, header=T)
jobs <- read.csv(file=file.jobs, header=T)
jobs$last_build_date <- as.POSIXct(jobs$last_build_time, origin="1970-01-01")
jobs$last_successful_build_date <- as.POSIXct(jobs$last_successful_build_time, origin="1970-01-01")
jobs$last_failed_build_date <- as.POSIXct(jobs$last_failed_build_time, origin="1970-01-01")
```

## Hudson Continuous Integration Engine

### Metrics

<p>
```{r metrics_table, echo=FALSE, message=FALSE, results='asis'}
t <- lapply(names(metrics), function(x) paste(x, ' <span class="badge">', metrics[[x]], '</span>, ', sep=''))
t <- paste(t, collapse=" ")
cat(t)
```
</p>

### Failing jobs

List of failing jobs, sorted by last successful build.

<div class="panel panel-default">
<div class="panel-heading" style="background-color: #3E3F3A; color: white"><span class="fa fa-indent"></span> Failing jobs</div>
<ul class="list-group">
```{r hudson_failing_jobs, echo=FALSE, message=FALSE, results='asis'}
# Filter nozbe tasks & get projects from task list.
t <- apply(jobs, 1, 
           function(x) paste('<li class="list-group-item"><i class="fa fa-thumbs-down"></i> ',
                             x[['name']], ' <small>', x[['last_build_date']], '</small><span class="pull-right"><span class="label label-success">',
                             x[['last_build_duration']], ' ms</span>', ' <span class="label" style="background-color: #cc6686">',
                             x[['health_report']], '</span></span></li>', sep=''))
t <- paste(t, collapse=" ")
cat(t)
```
</ul>
</div>
</div>

### Changed


### People

### Opened vs Closed

```{r evol, echo=FALSE, message=FALSE, results='asis', eval=F}
#if (nrow(evol) < 2) {
#  print( "No historical data found.")
#} else {
  evol.xts <- xts(evol, order.by = as.POSIXct(evol$unixtime, origin="1970-01-01"))
  p <-dygraph(evol.xts[,c(2:8)]) %>% dyRangeSelector()
  p
#}
```



```{r static-gvis, echo=FALSE, message=FALSE, results='asis', eval=F}
suppressPackageStartupMessages(library(googleVis))
options(gvis.plot.tag='chart')
my.chart <- evol[,c(1:8)]
p <- gvisLineChart(my.chart, options = list(
      title="Bugs",
      width=500, height=350
      ))

print(p, 'chart')
```

```{r ggplot, echo=FALSE, message=F, results='asis', eval=F}
my.data.long <- melt(evol[,c("unixtime", "opened", "closed")], id.vars="unixtime", value.name="value", variable.name="metric")
my.data.long$time <- as.POSIXct(as.numeric(as.character(my.data.long$unixtime)), origin="1970-01-01")

p <- ggplot(my.data.long, aes(x = time, y = value, color=metric)) + geom_line(size = .1)
p
```


<!-- iframe src="/projects/figures/eclipse_its/`r project.id`/its_evol_ggplot.html" frameborder="0" style="width: 800px; height: 500px"></iframe -->


```{r test, echo=FALSE, message=FALSE, results='asis', eval=F}
scatterplot3js(data[,c(3,6,1)],
               labels=row.names(mtcars),    # mousing over a point will show what model car it is
               size=mtcars$hp/100,          # the size of a point maps to horsepower
               flip.y=TRUE,
               color=col,renderer="canvas") # point color indicates number of cylindars 

data(economics, package = "ggplot2")
econ <- transform(economics, date = as.character(date))
m1 <- mPlot(x = "date", y = c("psavert", "uempmed"), type = "Line", data = econ)
m1$set(pointSize = 0, lineWidth = 1)
m1$print("chart2")
```

