---
output: html_document
---
```{r init, echo=FALSE, fig.height=3, message=FALSE, warning=FALSE}
#project.id <- 'alambic'
plugin.id <- 'SonarQube45'

abc <- c('A', 'B', 'C', 'D', 'E', 'F', 'G')

file.metrics = paste("", project.id, "_sq_metrics.csv", sep="")
metrics <- read.csv(file=file.metrics, header=T)
```

### <a name="quick-summary"></a>Quick Summary

``r ncol(metrics)`` metrics have been retrieved from SonarQube:

* Number of files ([SQ_FILES](/documentation/metrics#SQ_FILES)): ``r metrics[['SQ_FILES']]`` (average complexity: ``r metrics[['SQ_CPX_FILE_IDX']]``)
* Number of functions ([SQ_FUNCS](/documentation/metrics#SQ_FUNCS)): ``r metrics[['SQ_FUNCS']]`` (average complexity: ``r metrics[['SQ_CPX_FUNC_IDX']]``)
* Lines of code ([SQ_NCLOC](/documentation/metrics#SQ_NCLOC)): ``r metrics[['SQ_NCLOC']]``
* Statements ([SQ_STATEMENTS](/documentation/metrics#SQ_STATEMENTS)): ``r metrics[['SQ_STATEMENTS']]``

* Density of comments ([SQ_COMR](/documentation/metrics#SQ_COMR)): ``r metrics[['SQ_COMR']]``
* Density of comments on public API ([SQ_PUBLIC_API_DOC_DENSITY](/documentation/metrics#SQ_PUBLIC_API_DOC_DENSITY)): ``r metrics[['SQ_PUBLIC_API_DOC_DENSITY']]``
* Density of duplicated lines ([SQ_DUPLICATED_LINES_DENSITY](/documentation/metrics#SQ_DUPLICATED_LINES_DENSITY)): ``r metrics[['SQ_DUPLICATED_LINES_DENSITY']]``

* Number of unit tests ([SQ_TESTS](/documentation/metrics#SQ_TESTS)): ``r metrics[['SQ_TESTS']]``
* Percentage of successful tests ([SQ_TEST_SUCCESSFUL_DENSITY](/documentation/metrics#SQ_TEST_SUCCESSFUL_DENSITY)): ``r metrics[['SQ_TEST_SUCCESSFUL_DENSITY']]``
* Branch coverage ([SQ_COVERAGE](/documentation/metrics#SQ_COVERAGE)): ``r metrics[['SQ_COVERAGE']]``
* Branch coverage ([SQ_COVERAGE_BRANCH](/documentation/metrics#SQ_COVERAGE_BRANCH)): ``r metrics[['SQ_COVERAGE_BRANCH']]``
* Line coverage ([SQ_COVERAGE_LINE](/documentation/metrics#SQ_COVERAGE_LINE)): ``r metrics[['SQ_COVERAGE_LINE']]``

The SonarQube plugin analysis for project ``r project.id`` is available on the [Alambic dashboard](/projects/`r project.id`/SonarQubeIo/SonarQubeIo.html).
