
FROM boris/alambic
MAINTAINER Boris boris.baldassari@castalia.solutions

EXPOSE 3000

USER alambic
RUN su - alambic -c 'git clone https://bitbucket.org/BorisBaldassari/alambic.git'
COPY alambic.conf /home/alambic/alambic/mojo/alambic.conf
PGPASSWORD=pass4alambic psql -h postgres < ../resources/docker/psql_init.sql

#RUN hypnotoad script/alambic

ENTRYPOINT ["/usr/sbin/sshd", "-D"]


