
FROM centos:7
MAINTAINER Boris boris.baldassari@castalia.solutions

ENV container docker
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
VOLUME [ "/sys/fs/cgroup" ]

#EXPOSE 3000

# Install 
RUN yum -y update; yum clean all

# Install needed applications
RUN rpm -Uvh https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-7-x86_64/pgdg-centos95-9.5-3.noarch.rpm
RUN yum install -y openssh-server passwd postgresql95-server
RUN mkdir -p /var/run/sshd
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N '' 

#COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

#COPY set-psql-password.sh /tmp/set-psql-password.sh
#RUN /bin/sh /tmp/set-psql-password.sh

# Run script for alambic user, perlbrew and all mojo stuff
#COPY 00_init.sh /root/
#RUN chmod +x /root/00_init.sh
#RUN /root/00_init.sh

#ENTRYPOINT ["/bin/bash"]

CMD ["/usr/sbin/init"]
#CMD ["/usr/sbin/sshd", "-D"]
