pipeline {  

  environment {
    registry = "bbaldassari/alambic_base_centos"
    registryCredential = 'bbaldassari-dockerhub'
  }

  agent any

  stages {

    stage('Building image') {
      steps {
        script {
          dockerImage = docker.build( "$registry:$BUILD_NUMBER", "-f docker/image_base_centos/Dockerfile ." )
        }
      }
    }

    stage('Deploy Image') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
            dockerImage.push()
          }
        }
      }
    }

  }

}
