pipeline {  

  agent any

  environment {
    registry = "bbaldassari/alambic_base_centos"
    registryCredential = 'bbaldassari-dockerhub'
    def dockerTag = sh( script: "echo \$(date +%Y%m%d).${BUILD_NUMBER}", returnStdout: true).trim()
  }

  stages {

    stage('Build image') {
      steps {
        script {
          dockerImage = docker.build( "$registry:$dockerTag", "-f docker/image_base_centos/Dockerfile ." )
        }
      }
    }

    stage('Deploy Image') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
            dockerImage.push()
            dockerImage.push("latest")
          }
        }
      }
    }

  }

}
