
FROM alambic_base_centos:latest
MAINTAINER Boris boris.baldassari@castalia.solutions

EXPOSE 3000


# Switch to user alambic to install Perl
USER alambic

# Clone Alambic repository
RUN git clone https://bitbucket.org/BorisBaldassari/alambic.git /home/alambic/alambic
COPY alambic_start.sh /home/alambic/alambic_start.sh
COPY alambic_test.sh /home/alambic/alambic_test.sh
COPY alambic.conf /home/alambic/alambic/mojo/alambic.conf

# Execute tests
COPY ../../resources /root/alambic_test_wrapper.sh
RUN chmod +x /home/alambic/alambic_start.sh
RUN chmod +x /home/alambic/alambic_test.sh
RUN chmod +x /root/alambic_start_wrapper.sh
RUN chmod +x /root/alambic_test_wrapper.sh

# Install R and all dependencies
RUN rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm; \
	yum install -y R;
RUN yum install -y wget libcurl-devel

COPY alambic_install_r.R /home/alambic/
RUN Rscript /home/alambic/alambic_install_r.R



CMD ["/usr/sbin/sshd", "-D"]


