pipeline {  

  agent any

  environment {
    registry = "bbaldassari/alambic_test"
    registryCredential = 'bbaldassari-dockerhub'
    def dockerTag = sh( script: "echo \$(date +%Y%m%d).${BUILD_NUMBER}", returnStdout: true).trim()
  }

  stages {

    stage('Build image') {
      steps {
        script {
          dockerImage = docker.build( "$registry:latest", "-f docker/image_test/Dockerfile ." )
        }
      }
    }

    stage('Run tests') {
      steps {
        sh 'docker system prune --all --volumes -f'
        sh 'docker-compose -f docker-compose.test.yml run alambic_test'
      }
    }

    stage('Deploy Image') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
            dockerImage.push()
            dockerImage.push("latest")
          }
        }
      }
    }

  }

}
