pipeline {  

  environment {
    registry = "bbaldassari/alambic_test"
    registryCredential = 'bbaldassari-dockerhub'
  }

  agent any

  stages {

    stage('Build image') {
      steps {
        script {
          dockerImage = docker.build( "$registry:$BUILD_NUMBER", "-f docker/image_test/Dockerfile ." )
        }
      }
    }

    stage('Run tests') {
      steps {
        sh 'docker-compose -f docker-compose.test.yml'
      }
    }

    stage('Deploy Image') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
            dockerImage.push()
            dockerImage.push("latest")
          }
        }
      }
    }

  }

}
