pipeline {  

  environment {
    registry = "bbaldassari/alambic_test"
    registryCredential = 'bbaldassari-dockerhub'
  }

  agent any

  stages {
    stage('Building image') {
      steps {
        script {
          docker.build( "$registry:$BUILD_NUMBER", "-f docker/image_ci/Dockerfile ." )
        }
      }
    }
  }

}
